name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: growth-force-project
  FUNCTION_NAME: web-pixel-billing-batch
  REGION: asia-northeast1
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: growth-force-project
        workload_identity_provider: projects/32670171847/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-actions-deploy@growth-force-project.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy $FUNCTION_NAME \
          --gen2 \
          --runtime=nodejs18 \
          --region=$REGION \
          --source=. \
          --entry-point=processBilling \
          --trigger-http \
          --allow-unauthenticated \
          --memory=${{ secrets.FUNCTION_MEMORY || '256M' }} \
          --timeout=${{ secrets.FUNCTION_TIMEOUT || '540s' }} \
          --max-instances=1 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }},NODE_ENV=${{ secrets.NODE_ENV }}"

    - name: Create or update Cloud Scheduler job
      run: |
        # Get function trigger URL
        FUNCTION_URL=$(gcloud functions describe $FUNCTION_NAME --region=$REGION --format='value(serviceConfig.uri)')
        
        # Check if scheduler job exists
        if gcloud scheduler jobs describe shopify-billing-batch --location=$REGION --quiet 2>/dev/null; then
          echo "Updating existing scheduler job..."
          gcloud scheduler jobs update http shopify-billing-batch \
            --location=$REGION \
            --schedule="0 1 * * *" \
            --time-zone="Asia/Tokyo" \
            --uri="$FUNCTION_URL" \
            --http-method=POST \
            --headers="Content-Type=application/json" \
            --message-body="{}"
        else
          echo "Creating new scheduler job..."
          gcloud scheduler jobs create http shopify-billing-batch \
            --location=$REGION \
            --schedule="0 1 * * *" \
            --time-zone="Asia/Tokyo" \
            --uri="$FUNCTION_URL" \
            --http-method=POST \
            --headers="Content-Type=application/json" \
            --message-body="{}"
        fi

    - name: Output function URL
      run: |
        echo "Function deployed successfully!"
        gcloud functions describe $FUNCTION_NAME --region=$REGION --format='value(serviceConfig.uri)'