name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: growth-force-project
  SERVICE_NAME: web-pixel-billing-batch
  REGION: asia-northeast1
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1000m \
          --timeout 540s \
          --max-instances 1 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID" \
          --set-env-vars="NODE_ENV=production" \
          --set-env-vars="BILLING_RATE_PER_MILLION=10.0" \
          --set-env-vars="TIMEZONE=Asia/Tokyo" \
          --set-env-vars="BILLING_TIME=01:00"

    - name: Create or update Cloud Scheduler job
      run: |
        # Check if scheduler job exists
        if gcloud scheduler jobs describe shopify-billing-batch --location=$REGION --quiet 2>/dev/null; then
          echo "Updating existing scheduler job..."
          gcloud scheduler jobs update http shopify-billing-batch \
            --location=$REGION \
            --schedule="0 1 * * *" \
            --time-zone="Asia/Tokyo" \
            --uri="$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')/processBilling" \
            --http-method=POST \
            --headers="Content-Type=application/json" \
            --message-body="{}"
        else
          echo "Creating new scheduler job..."
          gcloud scheduler jobs create http shopify-billing-batch \
            --location=$REGION \
            --schedule="0 1 * * *" \
            --time-zone="Asia/Tokyo" \
            --uri="$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')/processBilling" \
            --http-method=POST \
            --headers="Content-Type=application/json" \
            --message-body="{}"
        fi

    - name: Output service URL
      run: |
        echo "Service deployed successfully!"
        gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)'