name: Test and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test
      continue-on-error: true  # テストは将来実装のため現在は失敗を許容

    - name: Build project
      run: npm run build

    - name: Verify build output
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed: dist directory not found"
          exit 1
        fi
        if [ ! -f "dist/index.js" ]; then
          echo "Build failed: dist/index.js not found"
          exit 1
        fi
        echo "Build successful: dist/index.js created"

    - name: Validate package.prod.json dependencies
      run: |
        echo "Validating package.prod.json dependencies..."
        # Extract runtime dependencies from package.json (excluding devDependencies)
        node -e "
          const pkg = require('./package.json');
          const prodPkg = require('./package.prod.json');
          
          const runtimeDeps = pkg.dependencies || {};
          const prodDeps = prodPkg.dependencies || {};
          
          console.log('Runtime dependencies in package.json:', Object.keys(runtimeDeps).length);
          console.log('Production dependencies in package.prod.json:', Object.keys(prodDeps).length);
          
          const missing = [];
          for (const dep of Object.keys(runtimeDeps)) {
            if (!prodDeps[dep]) {
              missing.push(dep);
            }
          }
          
          if (missing.length > 0) {
            console.error('Missing dependencies in package.prod.json:');
            missing.forEach(dep => console.error('  -', dep));
            process.exit(1);
          }
          
          console.log('✅ All runtime dependencies are present in package.prod.json');
        "

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 7